//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbuCheckPrototype
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportData
    {
        public int id { get; set; }
        public int reportId { get; set; }
        public int checkTypeId { get; set; }
        public string checkKey { get; set; }
        public Nullable<bool> checkBool { get; set; }
        public string checkString { get; set; }
        public string checkParent { get; set; }
        public string checkGrandparent { get; set; }
    
        public virtual CheckType CheckType { get; set; }
        public virtual Report Report { get; set; }
    }
}
