//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbuCheckPrototype
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Report()
        {
            this.ReportDatas = new HashSet<ReportData>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> dateTime { get; set; }
        public string crew1 { get; set; }
        public string crew2 { get; set; }
        public int ambulanceId { get; set; }
    
        public virtual Ambulance Ambulance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportData> ReportDatas { get; set; }
    }
}
